### ISSUE TITLE
Add Code Quality Measurement Tools

### ISSUE THREAD

**Issue by ethen001** [CodeletApp/codelet-app#6]
### Background
Since we are doing unit testing, we need to make sure we are testing as many of the components as possible, ideally,  100%. We need to keep track of our app's test coverage percent. Thus, if we see our coverage is very low, we take remediating action as less coverage correlates with more bugs.

### Task
* add Code Quality Measurement tools such as Code Climate to our project.

**Comment by Maker-Mark** [comment]
Looking into solutions for this.

**Comment by ethen001** [comment]
@Maker-Mark 
I think you should use [Code Climate.](https://codeclimate.com/) It is very easy to setup but I can't do it since I am not the owner

**Comment by Maker-Mark** [comment]
Added you as an owner to the organization. You should be able to manage third part access now.

**Comment by Maker-Mark** [comment]
Code climate was added.
Please reopen if that is incorrect.
